<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-27T09:11:08 EET" name="Default suite" finished-at="2025-01-27T09:11:08 EET" duration-ms="666">
    <groups>
    </groups>
    <test started-at="2025-01-27T09:11:08 EET" name="Default test" finished-at="2025-01-27T09:11:08 EET" duration-ms="666">
      <class name="MyFirstPackage.MyTestCases">
        <test-method is-config="true" signature="mySetup()[pri:0, instance:MyFirstPackage.MyTestCases@a514af7]" started-at="2025-01-27T09:11:08 EET" name="mySetup" finished-at="2025-01-27T09:11:08 EET" duration-ms="487" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mySetup -->
        <test-method signature="AddNewCustomer()[pri:1, instance:MyFirstPackage.MyTestCases@a514af7]" started-at="2025-01-27T09:11:08 EET" name="AddNewCustomer" finished-at="2025-01-27T09:11:08 EET" duration-ms="59" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '725' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '725' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyFirstPackage.MyTestCases.AddNewCustomer(MyTestCases.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddNewCustomer -->
        <test-method signature="UpdateCustomerInfo()[pri:2, instance:MyFirstPackage.MyTestCases@a514af7]" started-at="2025-01-27T09:11:08 EET" name="UpdateCustomerInfo" finished-at="2025-01-27T09:11:08 EET" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UpdateCustomerInfo -->
        <test-method signature="ReadTheUpdatedData()[pri:3, instance:MyFirstPackage.MyTestCases@a514af7]" started-at="2025-01-27T09:11:08 EET" name="ReadTheUpdatedData" finished-at="2025-01-27T09:11:08 EET" duration-ms="51" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReadTheUpdatedData -->
        <test-method signature="DeleteCustomer()[pri:4, instance:MyFirstPackage.MyTestCases@a514af7]" started-at="2025-01-27T09:11:08 EET" name="DeleteCustomer" finished-at="2025-01-27T09:11:08 EET" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteCustomer -->
      </class> <!-- MyFirstPackage.MyTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
